# -*- coding: utf-8 -*-
"""CÓDIGO SIMULACIÓN

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hQz6KtvsY3CFI3XV3OggS5-2szStkvJW

# 1. Carga de bibliotecas

Instalamos e importamos lo necesario para las fdp
"""

# Acá instalamos la biblioteca fitter para el ajuste de funciones
!pip install fitter

from fitter import Fitter
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats

from google.colab import drive
drive.mount('/content/drive')

"""# 2. Carga de datos

#### Utilizaremos los datos de llamadas a Soporte Técnico de Personal/Flow recibidas todos los días de diciembre 2025 entre las 00:00 y 23:59 hs para definir las fdp de cada uno de los motivos de llamado.
#### Se tendrán 4 simulaciones correspondientes a cada turno definido:

*   Turno Madrugada: 00:00 - 5:59
*   Turno Maniana:  6:00 - 11:59
*   Turno Tarde: 12:00 - 17:59
*   Turno Noche: 18:00 - 23:59

#### Por lo tanto, se definirán diferentes intervalos entre arribos para cada turno (considerando los atendidos y los abandonados).
####Se ocultan todos los datos sensibles y se obtienen solo los datos necesarios para realizar la simulacion





"""

# Importamos el dataset general
ds_general = pd.read_csv('/content/drive/MyDrive/TP_FINAL_DATASETS/202512_volumen_soporte.csv',sep=",")

"""# 3. Análisis Exploratorio y preparación de datos

### 3.1 Preparacion del dataset para el calculo de la fdp de los IA
"""

import pandas as pd
import numpy as np

# 1. Limpieza y Generación de Ruido (Granularidad)
ds_general['hora_limpia'] = ds_general['hora'].astype(str).str[:8]
ds_general['datetime'] = pd.to_datetime(ds_general['hora_limpia'], format='%H:%M:%S', errors='coerce')

np.random.seed(42)
random_seconds = np.random.randint(0, 60, size=len(ds_general))
random_millis = np.random.randint(0, 1000, size=len(ds_general))

ds_general['datetime_full'] = ds_general['datetime'] + \
                              pd.to_timedelta(random_seconds, unit='s') + \
                              pd.to_timedelta(random_millis, unit='ms')

ds_general['hora'] = ds_general['datetime_full'].dt.strftime('%H:%M:%S.%f').str[:-3]
ds_general['hora_entera'] = ds_general['datetime_full'].dt.hour

# 2. Cálculo de Arribo (ms)
conditions = [
    (ds_general['hora_entera'] >= 0) & (ds_general['hora_entera'] < 6),
    (ds_general['hora_entera'] >= 6) & (ds_general['hora_entera'] < 12),
    (ds_general['hora_entera'] >= 12) & (ds_general['hora_entera'] < 18),
    (ds_general['hora_entera'] >= 18) & (ds_general['hora_entera'] < 24)
]
choices = [0, 6, 12, 18]
ds_general['inicio_turno_hora'] = np.select(conditions, choices)
fecha_base = ds_general['datetime_full'].dt.normalize()
ds_general['inicio_turno_dt'] = fecha_base + pd.to_timedelta(ds_general['inicio_turno_hora'], unit='h')
ds_general['arribo_ms'] = (ds_general['datetime_full'] - ds_general['inicio_turno_dt']).dt.total_seconds() * 1000

# 3. Función de Procesamiento con FILTRO DE OUTLIERS
def procesar_turno_filtrado(df_turno, percentil=0.99):
    # a. Ordenar y calcular interarribos
    df_turno = df_turno.sort_values('arribo_ms').copy()
    df_turno['interarribo_ms'] = df_turno['arribo_ms'].diff()
    df_turno['interarribo_ms'] = df_turno['interarribo_ms'].fillna(df_turno['arribo_ms'])

    # b. FILTRADO: Calculamos el límite superior (Percentil 99)
    # Esto elimina el 1% de las esperas más largas que "aplastan" el histograma
    limite_superior = df_turno['interarribo_ms'].quantile(percentil)

    # c. Aplicamos el filtro
    df_filtrado = df_turno[df_turno['interarribo_ms'] <= limite_superior].copy()

    print(f"  > Registros originales: {len(df_turno)} | Filtrados (p{int(percentil*100)}): {len(df_filtrado)}")
    print(f"  > Corte de outlier: > {limite_superior:.2f} ms")

    return df_filtrado

# 4. Aplicación a cada turno
print("--- Procesando Turnos y Eliminando Valores Extremos ---")

print("Turno Madrugada:")
ds_madrugada = procesar_turno_filtrado(ds_general[(ds_general['hora_entera'] >= 0) & (ds_general['hora_entera'] < 6)])

print("\nTurno Mañana:")
ds_maniana = procesar_turno_filtrado(ds_general[(ds_general['hora_entera'] >= 6) & (ds_general['hora_entera'] < 12)])

print("\nTurno Tarde:")
ds_tarde = procesar_turno_filtrado(ds_general[(ds_general['hora_entera'] >= 12) & (ds_general['hora_entera'] < 18)])

print("\nTurno Noche:")
ds_noche = procesar_turno_filtrado(ds_general[(ds_general['hora_entera'] >= 18) & (ds_general['hora_entera'] < 24)])

# Verificación final
print(f"\n--- Totales Finales --- ")
print(f"Total Registros Limpios: {len(ds_madrugada)+len(ds_maniana)+len(ds_tarde)+len(ds_noche)}")

ds_general.head()

ds_madrugada.head()

ds_maniana.head()

ds_tarde.head()

ds_noche.head()

# Dimensionalidad del dataframe
ds_general.shape

ds_madrugada.shape

ds_maniana.shape

ds_tarde.shape

ds_noche.shape

ds_general.dtypes

"""### 3.2 Preparacion del dataset para el calculo de la fdp de los TA"""

# Definimos las categorías de interés (Tipos de Consulta) [SIN TABULACION son aquellos abandonados, por lo cual no tenemos su motivo de llamado]
categorias_interes = [
    "TECNICA INTERNET",
    "TECNICA CATV",
    "TECNICA FLOW",
    "AGENDA",
    "ACTIVIDAD COMERCIAL"
]

# Diccionario para almacenar los arrays de datos limpios por categoría
datos_ta_limpios = {}

print("INICIO DE LIMPIEZA Y FILTRADO DE OUTLIERS - TIEMPOS DE ATENCIÓN (TA)\n")

for cat in categorias_interes:
    # 1. Filtramos por la categoría actual
    df_cat = ds_general[ds_general['AGRUPADOR1'] == cat]

    # 2. Seleccionamos la columna de tiempos y eliminamos nulos
    data_raw = df_cat['TIEMPO_ATENCION'].dropna()

    # 3. FILTRO BÁSICO: Valores positivos (necesario para Lognormal/Gamma)
    data_pos = data_raw[data_raw > 0]

    # 4. FILTRO ESTADÍSTICO DE OUTLIERS (Percentil 99)
    # Eliminamos el 1% de las llamadas más largas que distorsionan el ajuste
    if len(data_pos) > 0:
        limite_superior = data_pos.quantile(0.99)
        data_clean = data_pos[data_pos <= limite_superior].values

        datos_ta_limpios[cat] = data_clean

        print(f"[{cat}]")
        print(f"  > Originales: {len(data_raw)} | Positivos: {len(data_pos)}")
        print(f"  > Filtrados (99%): {len(data_clean)} | Corte Outlier: > {limite_superior:.2f} seg")
    else:
        print(f"[{cat}] No hay datos válidos positivos.")

print("\nPreparación de datos completada. Listos para visualizar y ajustar.")

"""# 4. Visualización de Datos

### 4.1 Visualización de los Intervalos de Arribo (IA) por Turno
"""

import matplotlib.pyplot as plt

# Agrupamos los dataframes en un diccionario para iterar automáticamente
turnos_visualizacion = {
    "Madrugada (00-06)": ds_madrugada,
    "Mañana (06-12)": ds_maniana,
    "Tarde (12-18)": ds_tarde,
    "Noche (18-24)": ds_noche
}

print("ANÁLISIS EXPLORATORIO VISUAL DE LOS INTERVALOS ENTRE ARRIBOS (IA)\n")

plt.style.use('default')

for nombre_turno, df_turno in turnos_visualizacion.items():
    print(f"{'='*80}")
    print(f"ANÁLISIS DE TURNO: {nombre_turno}")

    # Extraemos la columna de interarribos y limpiamos posibles nulos de seguridad
    data_ia = df_turno['interarribo_ms'].dropna()

    if len(data_ia) == 0:
        print(f"[AVISO] Sin datos para el turno {nombre_turno}")
        continue

    # --- Configuración de Gráficos (Subplots) ---
    fig, axes = plt.subplots(1, 2, figsize=(12, 5))

    # GRÁFICO 1: Histograma (Izquierda)
    axes[0].hist(data_ia, bins=200, color='#1f77b4', edgecolor='black', alpha=0.7)
    axes[0].set_title(f"Histograma IA - {nombre_turno}")
    axes[0].set_xlabel("Intervalo entre Arribos (ms)")
    axes[0].set_ylabel("Frecuencia")
    axes[0].grid(axis='y', alpha=0.3)

    # GRÁFICO 2: Boxplot (Derecha)
    # Permite ver rápidamente la dispersión y los outliers
    axes[1].boxplot(data_ia, vert=True, patch_artist=True,
                    boxprops=dict(facecolor='#ff7f0e', color='black'),
                    medianprops=dict(color='blue', linewidth=2))
    axes[1].set_title(f"Boxplot IA - {nombre_turno}")
    axes[1].set_ylabel("Intervalo entre Arribos (ms)")
    axes[1].grid(axis='y', alpha=0.3)

    plt.tight_layout()
    plt.show()

    # --- Estadísticas Descriptivas ---
    print(f"\n>> Estadísticas descriptivas para {nombre_turno}:")
    print(data_ia.describe().round(2))
    print("\n")

"""### 4.2 Visualización de los Tiempos de Atención (TA) por Tipo de Consulta"""

import matplotlib.pyplot as plt
import pandas as pd # Necesario para convertir a Series y usar describe()

print("ANÁLISIS EXPLORATORIO VISUAL DE LOS TIEMPOS DE ATENCIÓN\n")

plt.style.use('default')

for cat, data in datos_ta_limpios.items():
    print(f"{'='*80}")
    print(f"ANÁLISIS DE CATEGORÍA: {cat}")

    series_data = pd.Series(data)

    # --- Gráfico 1: Histograma de Frecuencias ---
    plt.figure(figsize=(12, 5))

    # Subplot 1: Histograma
    plt.subplot(1, 2, 1)
    plt.hist(data, bins=500, color='#1f77b4', edgecolor='black', alpha=0.7)
    plt.title(f"Histograma - {cat}")
    plt.xlabel("Tiempo de Atención (segundos)")
    plt.ylabel("Frecuencia")
    plt.grid(axis='y', alpha=0.3)

    # Subplot 2: Boxplot (Diagrama de Caja y Bigotes)
    plt.subplot(1, 2, 2)
    plt.boxplot(data, vert=True, patch_artist=True,
                boxprops=dict(facecolor='#2ca02c', color='black'),
                medianprops=dict(color='yellow', linewidth=2))
    plt.title(f"Boxplot (Outliers) - {cat}")
    plt.ylabel("Tiempo de Atención (segundos)")
    plt.grid(axis='y', alpha=0.3)

    plt.tight_layout()
    plt.show()

    # --- Estadísticas Descriptivas ---
    # Esto es fundamental para entender la dispersión antes del ajuste
    print(f"\n>> Estadísticas descriptivas para {cat}:")
    print(series_data.describe().round(2))
    print("\n")

"""# 5. Ajuste de Datos

### 5.1 Ajuste de datos de los Intervalos de Arribo (IA) por Turno
"""

# --- AJUSTE DE FUNCIONES DE DENSIDAD DE PROBABILIDAD (FDP) PARA INTERVALOS ENTRE ARRIBOS (IA) ---

from fitter import Fitter, get_common_distributions
import matplotlib.pyplot as plt

# Diccionario para iterar sobre los 4 escenarios (Turnos)
# Se incluyen todos los turnos para asegurar la completitud del análisis, incluso los de baja demanda.
turnos_analisis = {
    "Madrugada (00-06)": ds_madrugada,
    "Mañana (06-12)": ds_maniana,
    "Tarde (12-18)": ds_tarde,
    "Noche (18-24)": ds_noche
}

plt.style.use('default')

# Diccionario para almacenar los parámetros de la mejor distribución de cada turno
resultados_ia = {}

# Definimos las distribuciones teóricas a testear.
# Se incluye 'expon' (Exponencial) por ser la distribución teórica estándar para procesos de Poisson (llegadas).
# Se incluyen 'gamma', 'lognorm' y 'weibull_min' por su flexibilidad para modelar tiempos positivos asimétricos.
distribuciones_a_testear = ['expon', 'gamma', 'lognorm', 'weibull_min', 'norm']

print("INICIO DEL ANÁLISIS DE AJUSTE DE CURVAS (IA)\n")

for nombre_turno, df_turno in turnos_analisis.items():
    print(f"{'='*60}")
    print(f"PROCESANDO TURNO: {nombre_turno}")

    # Validación de seguridad: Verificar si existen datos suficientes para el ajuste
    data_ia = df_turno['interarribo_ms'].dropna().values

    if len(data_ia) < 50:
        print(f"[AVISO] El turno {nombre_turno} posee muestras insuficientes ({len(data_ia)}) para un ajuste estadístico robusto.")
        # Se podría asignar una distribución por defecto si fuera necesario, o saltar.
        continue

    # Instanciamos el objeto Fitter
    # timeout=120 segundos para evitar que Colab se corte si el cálculo es muy complejo
    f = Fitter(data_ia,
               distributions=distribuciones_a_testear,
               timeout=120)

    # Ejecutamos el ajuste
    f.fit()

    # Visualización de resultados para el informe
    print(f"Resumen de ajuste para {nombre_turno}:")
    print(f.summary()) # Genera la tabla comparativa y el gráfico de las curvas

    # Obtenemos la mejor distribución basada en el menor error cuadrático (Sum of Square Error)
    mejor_dist = f.get_best(method='sumsquare_error')

    # Guardamos el resultado para utilizarlo posteriormente en la simulación
    resultados_ia[nombre_turno] = mejor_dist

    print(f"\n>> MEJOR AJUSTE SELECCIONADO: {mejor_dist}")

    # Mostramos el gráfico
    plt.title(f"Ajuste de Distribución - IA - {nombre_turno}")
    plt.xlabel("Intervalo entre Arribos (ms)")
    plt.ylabel("Densidad")
    plt.show()
    print("\n")

print(f"{'='*60}")
print("RESULTADOS FINALES DE LOS PARÁMETROS IA PARA LA SIMULACIÓN:")
for turno, params in resultados_ia.items():
    print(f"{turno}: {params}")

# --- GRAYSCALE - PAPER ---
import matplotlib.pyplot as plt
import numpy as np
from fitter import Fitter
import scipy.stats as stats

# Configuración de estilo
plt.style.use('grayscale')

print("GENERACIÓN DE MODELOS (IA)\n")

for nombre, df in turnos_analisis.items():
    print(f"{'='*80}")
    print(f"PROCESANDO TURNO: {nombre}")

    # 1. DATOS ORIGINALES
    data = df['interarribo_ms'].dropna().astype(float).values

    if len(data) < 50:
        print("[SKIP] Pocos datos.")
        continue

    # 2. FIT
    f = Fitter(data, distributions=['lognorm', 'gamma', 'weibull_min', 'expon', 'norm'], timeout=120)
    f.fit()

    best_dist_name = list(f.get_best(method='sumsquare_error').keys())[0]
    best_params = f.fitted_param[best_dist_name]

    print(f"Ganadora: {best_dist_name}")
    print(f"Parámetros: {best_params}")

    # 3. GRAFICAR
    dist_model = getattr(stats, best_dist_name)

    x = np.linspace(data.min(), data.max(), 1000)
    pdf = dist_model.pdf(x, *best_params)

    plt.figure(figsize=(10, 6))

    # a. Histograma: Guardamos los valores de retorno (n = alturas)
    n, bins, patches = plt.hist(data, bins=100, density=True, alpha=0.5, label=f'Datos {nombre}')

    # b. Curva
    plt.plot(x, pdf, 'k-', lw=2, label=f'Ajuste {best_dist_name}')

    # c. CORRECCIÓN DE ESCALA Y (ZOOM AUTOMÁTICO)
    # Si la curva se dispara (asíntota en 0), cortamos la vista a la altura de las barras
    max_altura_barras = n.max()
    plt.ylim(0, max_altura_barras * 1.2) # Dejamos un 20% de aire arriba de la barra más alta

    plt.title(f"Ajuste FDP - IA ({nombre}) - {best_dist_name}")
    plt.legend()
    plt.grid(alpha=0.2)
    plt.show()

    # 4. Validación
    simulados = dist_model.rvs(*best_params, size=10)
    print(f"Muestras: {np.round(simulados, 2)}\n")

"""###5.2 Ajuste de datos del Tiempo de Atención (TA) por Tipo de Consulta [*General*]"""

from fitter import Fitter

# Diccionario para guardar los resultados (los usarás en la simulación)
resultados_ta = {}

# Distribuciones candidatas para tiempos de servicio
# 'lognorm' y 'gamma' suelen ser las mejores para tiempos humanos (colas largas a la derecha)
distribuciones_ta = ['gamma', 'lognorm', 'weibull_min', 'expon', 'norm','moyal']

print("INICIO DEL AJUSTE DE CURVAS PARA TIEMPOS DE ATENCIÓN (TA)\n")

plt.style.use('default')

for cat in categorias_interes:
    print(f"{'='*60}")
    print(f"AJUSTANDO DISTRIBUCIÓN PARA: {cat}")

    # Obtenemos los datos limpios
    data_ta = ds_general[ds_general['AGRUPADOR1'] == cat]['TIEMPO_ATENCION'].dropna().values

    # Validación de cantidad de datos
    if len(data_ta) < 50:
        print(f"[SKIP] Pocos datos para ajustar {cat} ({len(data_ta)} muestras).")
        continue

    # Instanciamos Fitter
    f = Fitter(data_ta, distributions=distribuciones_ta, timeout=120)
    f.fit()

    # Mostramos el resumen
    print(f.summary())

    # Guardamos la mejor
    best_dist = f.get_best(method='sumsquare_error')
    resultados_ta[cat] = best_dist

    print(f"\n>> MEJOR AJUSTE PARA {cat}: {best_dist}")

    # Mostramos el gráfico comparativo
    plt.title(f"Ajuste Fitter - {cat}")
    plt.xlabel("Segundos")
    plt.ylabel("Densidad")
    plt.show()
    print("\n")

print(f"{'='*60}")
print("PARÁMETROS FINALES DE TA PARA LA SIMULACIÓN:")
for k, v in resultados_ta.items():
    print(f"{k}: {v}")

# --- GRAYSCALE - PAPER ---

categorias_interes = ["TECNICA INTERNET", "TECNICA CATV", "TECNICA FLOW", "AGENDA", "ACTIVIDAD COMERCIAL"]

plt.style.use('grayscale')

print("GENERACIÓN DE MODELOS Y GRÁFICOS (TA) - CONSISTENTE\n")

for cat in categorias_interes:
    print(f"{'='*80}")
    print(f"PROCESANDO CATEGORÍA: {cat}")

    # 1. Preparación
    data = ds_general[ds_general['AGRUPADOR1'] == cat]['TIEMPO_ATENCION'].dropna().astype(float).values

    # Solo filtramos negativos reales, pero 0 lo tratamos con epsilon si existe
    data = data[data >= 0]
    data[data == 0] = 0.01

    if len(data) < 50:
        print(f"[SKIP] Pocos datos para {cat}.")
        continue

    # 2. Fit
    f = Fitter(data, distributions=['lognorm', 'gamma', 'weibull_min', 'expon', 'norm'], timeout=120)
    f.fit()

    best_dist_name = list(f.get_best(method='sumsquare_error').keys())[0]
    best_params = f.fitted_param[best_dist_name]

    print(f"Distribución ganadora: {best_dist_name}")
    print(f"Parámetros: {f.get_best(method='sumsquare_error')[best_dist_name]}")

    # 3. Graficar
    dist_model = getattr(stats, best_dist_name)
    x = np.linspace(data.min(), data.max(), 300)
    pdf = dist_model.pdf(x, *best_params)

    plt.figure(figsize=(10, 6))
    plt.hist(data, bins=200, density=True, alpha=0.5, label=f'Datos {cat}')
    plt.plot(x, pdf, 'k-', lw=2, label=f'{best_dist_name} ajustada')

    plt.title(f"Ajuste FDP - TA ({cat}) - {best_dist_name}")
    plt.legend()
    plt.grid(alpha=0.2)
    plt.show()

    # 4. Validación
    simulados = dist_model.rvs(*best_params, size=10)
    print(f"Muestras simuladas: {np.round(simulados, 2)}\n")

"""# 6. Simulación del Modelo

### 6.1 Configuración de la Simulación
"""

# --- 6.1 CONFIGURACIÓN DEL MODELO Y HELPERS ---

import random
import math
import numpy as np

print("Cargando generadores y reglas de negocio con corrección temporal...")

# ---------------------------------------------------------
# 1. GENERADORES DE TIEMPO (FDPs Ajustadas)
# ---------------------------------------------------------
# CORRECCIÓN: (valor_ms / 1000) * 31 días para obtener el IA real en segundos por día

def generar_ia_madrugada():
    val_ms = max(0, random.lognormvariate(math.log(1687.3469), 1.4185) - 30.7713)
    return (val_ms / 1000.0) * 31.0

def generar_ia_maniana():
    val_ms = random.weibullvariate(290.6916, 0.8947)
    return (val_ms / 1000.0) * 31.0

def generar_ia_tarde():
    val_ms = random.gammavariate(1.0301, 209.7228)
    return (val_ms / 1000.0) * 31.0

def generar_ia_noche():
    val_ms = random.weibullvariate(291.9040, 0.9699)
    return (val_ms / 1000.0) * 31.0

# Los TA ya estaban en segundos, se mantienen intactos
def generar_ta_tecnica_internet(): return max(0, random.lognormvariate(math.log(4313.9606), 0.5637) - 751.2319)
def generar_ta_tecnica_catv():     return max(0, random.lognormvariate(math.log(3718.3236), 0.5292) - 701.4885)
def generar_ta_tecnica_flow():     return max(0, random.lognormvariate(math.log(4566.4092), 0.5607) - 807.2023)
def generar_ta_agenda():           return max(0, random.lognormvariate(math.log(2792.0761), 0.5983) - 312.2966)
def generar_ta_comercial():        return max(0, random.weibullvariate(2915.8499, 1.0465) + 47.9759)

# ---------------------------------------------------------
# 2. HELPERS DE LÓGICA DE NEGOCIO
# ---------------------------------------------------------
def obtener_tipo_consulta():
    r = random.random()
    if r <= 0.52: return "TECNICA INTERNET"
    elif r <= 0.74: return "TECNICA FLOW"
    elif r <= 0.83: return "ACTIVIDAD COMERCIAL"
    elif r <= 0.92: return "TECNICA CATV"
    else: return "AGENDA"

def obtener_tiempo_base(tipo_consulta):
    if tipo_consulta == "TECNICA INTERNET": return generar_ta_tecnica_internet()
    elif tipo_consulta == "TECNICA CATV": return generar_ta_tecnica_catv()
    elif tipo_consulta == "TECNICA FLOW": return generar_ta_tecnica_flow()
    elif tipo_consulta == "AGENDA": return generar_ta_agenda()
    elif tipo_consulta == "ACTIVIDAD COMERCIAL": return generar_ta_comercial()
    return 0

def evaluar_arrepentimiento(llamadas_en_espera):
    prob_abandono = 0.0
    if llamadas_en_espera <= 1: prob_abandono = 0.00
    elif llamadas_en_espera <= 15: prob_abandono = 0.08
    elif llamadas_en_espera <= 40: prob_abandono = 0.34
    else: prob_abandono = 0.66
    return random.random() < prob_abandono

def calcular_tiempo_junior(tiempo_base):
    penalizacion = random.uniform(0.15, 0.30)
    return tiempo_base * (1 + penalizacion)

def procesar_logica_ia(tiempo_base, es_madrugada):
    mejora_ia = random.triangular(0.10, 0.25, 0.30)
    tiempo_ia = tiempo_base * (1 - mejora_ia)
    r = random.random()
    if r < 0.65: estado = 'RESUELTO'
    elif r < 0.75: estado = 'FALLO' if es_madrugada else 'DERIVADO'
    else: estado = 'FALLO'
    return estado, tiempo_ia

"""### 6.2 Código de la Simulación"""

# --- 6.2 MOTOR DE SIMULACIÓN (EVENTO A EVENTO PURO) CON CAPACITACIÓN ---
import random

def simular_turno(nombre_turno, NSR, NJR, NIA, fn_generar_ia, cursos_activos=False):
    HV = float('inf')
    T = 0.0
    TF = 21600 * 365

    TPLL = 0.0
    TPSO = [HV] * (NSR + NJR) if (NSR + NJR) > 0 else []
    TPSIA = [HV] * NIA if NIA > 0 else []
    ESTADO_IA = [''] * NIA

    # --- NUEVA LÓGICA: VECTOR DE MEJORA POR CAPACITACIÓN ---
    MEJORA_OP = [0.0] * (NSR + NJR)
    if cursos_activos:
        for i in range(NSR + NJR):
            if i < NJR:
                # Junior: Mejora entre 2% y 10% (Moda 6%)
                MEJORA_OP[i] = random.triangular(0.02, 0.06, 0.10)
            else:
                # Senior: Mejora entre 1% y 5% (Moda 3%)
                MEJORA_OP[i] = random.triangular(0.01, 0.03, 0.05)

    NS = 0; NSP = 0; NSO = 0; NSIA = 0
    NTSr = 0; NTJr = 0; NTIA_A = 0; NTIA_D = 0; NTIA_F = 0; ARRE = 0

    ITOO = [0.0] * (NSR + NJR)
    STOO = [0.0] * (NSR + NJR)
    ITOIA = [0.0] * NIA
    STOIA = [0.0] * NIA

    es_madrugada = (NSR + NJR == 0)

    while T < TF or NS > 0:
        min_TPSO = min(TPSO) if TPSO else HV
        min_TPSIA = min(TPSIA) if TPSIA else HV

        T = min(TPLL, min_TPSO, min_TPSIA)

        if T >= TF and TPLL != HV:
            TPLL = HV

        if T == TPLL and TPLL != HV:
            TPLL = T + fn_generar_ia()
            if TPLL >= TF:
                TPLL = HV

            llamadas_en_espera = NS - NSO - NSIA
            if evaluar_arrepentimiento(llamadas_en_espera):
                ARRE += 1
            else:
                NS += 1

                if NSO < (NSR + NJR):
                    NSO += 1
                    libres = [i for i, t in enumerate(TPSO) if t == HV]
                    idx_elegido = max(libres, key=lambda i: STOO[i])

                    tipo_consulta = obtener_tipo_consulta()
                    t_base = obtener_tiempo_base(tipo_consulta)
                    es_junior = idx_elegido < NJR
                    TA = calcular_tiempo_junior(t_base) if es_junior else t_base

                    TA = TA * (1 - MEJORA_OP[idx_elegido])

                    TPSO[idx_elegido] = T + TA
                    STOO[idx_elegido] += T - ITOO[idx_elegido]

                elif NSIA < NIA:
                    NSIA += 1
                    libres_ia = [i for i, t in enumerate(TPSIA) if t == HV]
                    idx_ia = max(libres_ia, key=lambda i: STOIA[i])

                    tipo_consulta = obtener_tipo_consulta()
                    t_base = obtener_tiempo_base(tipo_consulta)
                    estado, TA = procesar_logica_ia(t_base, es_madrugada)

                    ESTADO_IA[idx_ia] = estado
                    TPSIA[idx_ia] = T + TA
                    STOIA[idx_ia] += T - ITOIA[idx_ia]

        elif T == min_TPSO and TPSO and T != HV:
            idx = TPSO.index(T)
            NS -= 1
            NSO -= 1

            if idx < NJR: NTJr += 1
            else: NTSr += 1

            if NSP > 0 or (NS - NSO - NSIA) > 0:
                if NSP > 0: NSP -= 1
                NSO += 1
                tipo_consulta = obtener_tipo_consulta()
                t_base = obtener_tiempo_base(tipo_consulta)
                es_junior = idx < NJR
                TA = calcular_tiempo_junior(t_base) if es_junior else t_base

                TA = TA * (1 - MEJORA_OP[idx])

                TPSO[idx] = T + TA
            else:
                TPSO[idx] = HV
                ITOO[idx] = T

        elif T == min_TPSIA and TPSIA and T != HV:
            idx_ia = TPSIA.index(T)
            estado = ESTADO_IA[idx_ia]
            NSIA -= 1

            if estado == 'RESUELTO':
                NTIA_A += 1
                NS -= 1
            elif estado == 'FALLO':
                NTIA_F += 1
                NS -= 1
            elif estado == 'DERIVADO':
                NTIA_D += 1
                if NSO < (NSR + NJR):
                    NSO += 1
                    libres = [i for i, t in enumerate(TPSO) if t == HV]
                    idx_op = max(libres, key=lambda i: STOO[i])
                    tipo_consulta = obtener_tipo_consulta()
                    t_base = obtener_tiempo_base(tipo_consulta)
                    TA = calcular_tiempo_junior(t_base) if idx_op < NJR else t_base

                    TA = TA * (1 - MEJORA_OP[idx_op])

                    TPSO[idx_op] = T + TA
                    STOO[idx_op] += T - ITOO[idx_op]
                else:
                    NSP += 1

            if (NS - NSO - NSP - NSIA) > 0:
                NSIA += 1
                tipo_consulta = obtener_tipo_consulta()
                t_base = obtener_tiempo_base(tipo_consulta)
                nuevo_estado, TA = procesar_logica_ia(t_base, es_madrugada)
                ESTADO_IA[idx_ia] = nuevo_estado
                TPSIA[idx_ia] = T + TA
            else:
                TPSIA[idx_ia] = HV
                ITOIA[idx_ia] = T

    for i in range(NSR + NJR):
        if TPSO[i] == HV: STOO[i] += (T - ITOO[i])
    for j in range(NIA):
        if TPSIA[j] == HV: STOIA[j] += (T - ITOIA[j])

    STOSr = sum(STOO[NJR:NJR+NSR]) if NSR > 0 else 0
    STOJr = sum(STOO[0:NJR]) if NJR > 0 else 0
    STOIA_Total = sum(STOIA) if NIA > 0 else 0
    NTIA = NTIA_A + NTIA_D + NTIA_F

    PASr = (NTSr / (NTSr + ARRE) * 100) if (NTSr + ARRE) > 0 else 0
    PTOSr = (STOSr / (T * NSR) * 100) if NSR > 0 else 0
    PAJr = (NTJr / (NTJr + ARRE) * 100) if (NTJr + ARRE) > 0 else 0
    PTOJr = (STOJr / (T * NJR) * 100) if NJR > 0 else 0
    PTOIA_pct = (STOIA_Total / (T * NIA) * 100) if NIA > 0 else 0
    PCR = (NTIA_A / NTIA * 100) if NTIA > 0 else 0
    PCD = (NTIA_D / NTIA * 100) if NTIA > 0 else 0
    PCF = (NTIA_F / NTIA * 100) if NTIA > 0 else 0

    Total_Atendidos = NTSr + NTJr + NTIA_A + NTIA_F
    PA = (Total_Atendidos / (Total_Atendidos + ARRE) * 100) if (Total_Atendidos + ARRE) > 0 else 0

    capacidad_total = NSR + NJR + NIA
    PTO = ((STOSr + STOJr + STOIA_Total) / (T * capacidad_total) * 100) if capacidad_total > 0 else 0

    return {
        "Turno": nombre_turno,
        "SLA (PA)": round(PA, 2),
        "Arrepentidos": ARRE,
        "Total Atendidos": Total_Atendidos,
        "Atendidos Sr": NTSr,
        "Atendidos Jr": NTJr,
        "Atendidos IA (Total)": NTIA,
        "IA Resueltos (%)": round(PCR, 2),
        "IA Derivados (%)": round(PCD, 2),
        "IA Fallos (%)": round(PCF, 2),
        "PTO General (%)": round(PTO, 2),
        "PTO Seniors (%)": round(PTOSr, 2),
        "PTO Juniors (%)": round(PTOJr, 2),
        "PTO IA (%)": round(PTOIA_pct, 2)
    }

"""# 7. Resultados"""

# --- 7. EJECUCIÓN DE ESCENARIOS Y ANÁLISIS ECONÓMICO (UNIFICADO) ---

import pandas as pd

print("Iniciando BATERÍA DE SIMULACIONES: 3 Modelos Estratégicos...")
print("1. SIN IA")
print("2. CON IA")
print("3. CON IA + CURSOS")
print("Esto tomará varios minutos. Procesando turno a turno...\n")

# --- COSTOS CORPORATIVOS ---
COSTO_ANUAL_SENIOR = 12090000 #13 sueldos de ARS 930.000
COSTO_ANUAL_JUNIOR = 8060000 #13 sueldos de ARS 620.000
COSTO_ANUAL_IA = 138996000     # $11.583.000 * 12
COSTO_ANUAL_CURSO_POR_OP = 400000 # E-learning + Bono Semestral

# --- MATRIZ UNIFICADA DE LOS 3 MODELOS---
escenarios_unificados = [
    # ==========================================================
    # MODELO 1: SIN IA (NUESTRA BASE ESTRUCTURAL)
    # ==========================================================
    {"Tipo": "SIN IA", "Cursos": False, "Turno": "Madrugada", "NSR": 0, "NJR": 37, "NIA": 0, "Desc": "Premium (~92%)"},
    {"Tipo": "SIN IA", "Cursos": False, "Turno": "Madrugada", "NSR": 0, "NJR": 35, "NIA": 0, "Desc": "Equilibrado (~90%)"},
    {"Tipo": "SIN IA", "Cursos": False, "Turno": "Madrugada", "NSR": 0, "NJR": 34, "NIA": 0, "Desc": "Low Cost (~87%)"},

    {"Tipo": "SIN IA", "Cursos": False, "Turno": "Mañana", "NSR": 50, "NJR": 424, "NIA": 0, "Desc": "Premium (~92%)"},
    {"Tipo": "SIN IA", "Cursos": False, "Turno": "Mañana", "NSR": 50, "NJR": 414, "NIA": 0, "Desc": "Equilibrado (~90%)"},
    {"Tipo": "SIN IA", "Cursos": False, "Turno": "Mañana", "NSR": 50, "NJR": 396, "NIA": 0, "Desc": "Low Cost (~87%)"},

    {"Tipo": "SIN IA", "Cursos": False, "Turno": "Tarde", "NSR": 100, "NJR": 564, "NIA": 0, "Desc": "Premium (~92%)"},
    {"Tipo": "SIN IA", "Cursos": False, "Turno": "Tarde", "NSR": 100, "NJR": 549, "NIA": 0, "Desc": "Equilibrado (~90%)"},
    {"Tipo": "SIN IA", "Cursos": False, "Turno": "Tarde", "NSR": 100, "NJR": 526, "NIA": 0, "Desc": "Low Cost (~87%)"},

    {"Tipo": "SIN IA", "Cursos": False, "Turno": "Noche", "NSR": 50, "NJR": 440, "NIA": 0, "Desc": "Premium (~92%)"},
    {"Tipo": "SIN IA", "Cursos": False, "Turno": "Noche", "NSR": 50, "NJR": 430, "NIA": 0, "Desc": "Equilibrado (~90%)"},
    {"Tipo": "SIN IA", "Cursos": False, "Turno": "Noche", "NSR": 50, "NJR": 414, "NIA": 0, "Desc": "Low Cost (~87%)"},

    # ==========================================================
    # MODELO 2: CON IA (SENIORS FIJADOS = SOLO CAE LA NECESIDAD DE JUNIORS)
    # ==========================================================
    {"Tipo": "CON IA", "Cursos": False, "Turno": "Madrugada", "NSR": 0, "NJR": 9,  "NIA": 20, "Desc": "Premium (~92%)"},
    {"Tipo": "CON IA", "Cursos": False, "Turno": "Madrugada", "NSR": 0, "NJR": 8,  "NIA": 20, "Desc": "Equilibrado (~90%)"},
    {"Tipo": "CON IA", "Cursos": False, "Turno": "Madrugada", "NSR": 0, "NJR": 6,  "NIA": 20, "Desc": "Low Cost (~87%)"},

    {"Tipo": "CON IA", "Cursos": False, "Turno": "Mañana", "NSR": 50, "NJR": 395, "NIA": 20, "Desc": "Premium (~92%)"},
    {"Tipo": "CON IA", "Cursos": False, "Turno": "Mañana", "NSR": 50, "NJR": 384, "NIA": 20, "Desc": "Equilibrado (~90%)"},
    {"Tipo": "CON IA", "Cursos": False, "Turno": "Mañana", "NSR": 50, "NJR": 368, "NIA": 20, "Desc": "Low Cost (~87%)"},

    {"Tipo": "CON IA", "Cursos": False, "Turno": "Tarde", "NSR": 100, "NJR": 530, "NIA": 20, "Desc": "Premium (~92%)"},
    {"Tipo": "CON IA", "Cursos": False, "Turno": "Tarde", "NSR": 100, "NJR": 520, "NIA": 20, "Desc": "Equilibrado (~90%)"},
    {"Tipo": "CON IA", "Cursos": False, "Turno": "Tarde", "NSR": 100, "NJR": 498, "NIA": 20, "Desc": "Low Cost (~87%)"},

    {"Tipo": "CON IA", "Cursos": False, "Turno": "Noche", "NSR": 50, "NJR": 412, "NIA": 20, "Desc": "Premium (~92%)"},
    {"Tipo": "CON IA", "Cursos": False, "Turno": "Noche", "NSR": 50, "NJR": 401, "NIA": 20, "Desc": "Equilibrado (~90%)"},
    {"Tipo": "CON IA", "Cursos": False, "Turno": "Noche", "NSR": 50, "NJR": 385, "NIA": 20, "Desc": "Low Cost (~87%)"},
    # ==========================================================
    # MODELO 3: CON IA + CURSOS (SENIORS FIJADOS = CAEN AÚN MÁS LOS JUNIORS)
    # ==========================================================
    {"Tipo": "CON IA + CURSOS", "Cursos": True, "Turno": "Madrugada", "NSR": 0, "NJR": 9, "NIA": 20, "Desc": "Premium (~92%)"},
    {"Tipo": "CON IA + CURSOS", "Cursos": True, "Turno": "Madrugada", "NSR": 0, "NJR": 7, "NIA": 20, "Desc": "Equilibrado (~90%)"},
    {"Tipo": "CON IA + CURSOS", "Cursos": True, "Turno": "Madrugada", "NSR": 0, "NJR": 6, "NIA": 20, "Desc": "Low Cost (~87%)"},

    {"Tipo": "CON IA + CURSOS", "Cursos": True, "Turno": "Mañana", "NSR": 50, "NJR": 371, "NIA": 20, "Desc": "Premium (~92%)"},
    {"Tipo": "CON IA + CURSOS", "Cursos": True, "Turno": "Mañana", "NSR": 50, "NJR": 362, "NIA": 20, "Desc": "Equilibrado (~90%)"},
    {"Tipo": "CON IA + CURSOS", "Cursos": True, "Turno": "Mañana", "NSR": 50, "NJR": 347, "NIA": 20, "Desc": "Low Cost (~87%)"},

    {"Tipo": "CON IA + CURSOS", "Cursos": True, "Turno": "Tarde", "NSR": 100, "NJR": 504, "NIA": 20, "Desc": "Premium (~92%)"},
    {"Tipo": "CON IA + CURSOS", "Cursos": True, "Turno": "Tarde", "NSR": 100, "NJR": 489, "NIA": 20, "Desc": "Equilibrado (~90%)"},
    {"Tipo": "CON IA + CURSOS", "Cursos": True, "Turno": "Tarde", "NSR": 100, "NJR": 467, "NIA": 20, "Desc": "Low Cost (~87%)"},

    {"Tipo": "CON IA + CURSOS", "Cursos": True, "Turno": "Noche", "NSR": 50, "NJR": 389, "NIA": 20, "Desc": "Premium (~92%)"},
    {"Tipo": "CON IA + CURSOS", "Cursos": True, "Turno": "Noche", "NSR": 50, "NJR": 378, "NIA": 20, "Desc": "Equilibrado (~90%)"},
    {"Tipo": "CON IA + CURSOS", "Cursos": True, "Turno": "Noche", "NSR": 50, "NJR": 362, "NIA": 20, "Desc": "Low Cost (~87%)"}
]

escenarios_curva = [
    # --- MADRUGADA (Seniors Fijos = 0) ---
    {"Tipo": "CON IA + CURSOS", "Cursos": True, "Turno": "Madrugada", "NSR": 0, "NJR": 4,  "NIA": 20, "Desc": "1. Base (~84%)"},
    {"Tipo": "CON IA + CURSOS", "Cursos": True, "Turno": "Madrugada", "NSR": 0, "NJR": 5,  "NIA": 20, "Desc": "2. Pre-Low Cost (~86%)"},
    {"Tipo": "CON IA + CURSOS", "Cursos": True, "Turno": "Madrugada", "NSR": 0, "NJR": 6,  "NIA": 20, "Desc": "3. Low Cost (~88%)"},
    {"Tipo": "CON IA + CURSOS", "Cursos": True, "Turno": "Madrugada", "NSR": 0, "NJR": 7,  "NIA": 20, "Desc": "4. Equilibrado (~90%)"},
    {"Tipo": "CON IA + CURSOS", "Cursos": True, "Turno": "Madrugada", "NSR": 0, "NJR": 8,  "NIA": 20, "Desc": "5. Intermedio (~91%)"},
    {"Tipo": "CON IA + CURSOS", "Cursos": True, "Turno": "Madrugada", "NSR": 0, "NJR": 9,  "NIA": 20, "Desc": "6. Premium (~93%)"},
    {"Tipo": "CON IA + CURSOS", "Cursos": True, "Turno": "Madrugada", "NSR": 0, "NJR": 10, "NIA": 20, "Desc": "7. Ultra (~94%)"},
    {"Tipo": "CON IA + CURSOS", "Cursos": True, "Turno": "Madrugada", "NSR": 0, "NJR": 11, "NIA": 20, "Desc": "8. Max (~95%)"},

    # --- MAÑANA (Seniors Fijos = 50) ---
    {"Tipo": "CON IA + CURSOS", "Cursos": True, "Turno": "Mañana", "NSR": 50, "NJR": 330, "NIA": 20, "Desc": "1. Base (~84%)"},
    {"Tipo": "CON IA + CURSOS", "Cursos": True, "Turno": "Mañana", "NSR": 50, "NJR": 338, "NIA": 20, "Desc": "2. Pre-Low Cost (~85.5%)"},
    {"Tipo": "CON IA + CURSOS", "Cursos": True, "Turno": "Mañana", "NSR": 50, "NJR": 347, "NIA": 20, "Desc": "3. Low Cost (~87%)"},
    {"Tipo": "CON IA + CURSOS", "Cursos": True, "Turno": "Mañana", "NSR": 50, "NJR": 354, "NIA": 20, "Desc": "4. Intermedio 1 (~88.5%)"},
    {"Tipo": "CON IA + CURSOS", "Cursos": True, "Turno": "Mañana", "NSR": 50, "NJR": 362, "NIA": 20, "Desc": "5. Equilibrado (~90%)"},
    {"Tipo": "CON IA + CURSOS", "Cursos": True, "Turno": "Mañana", "NSR": 50, "NJR": 371, "NIA": 20, "Desc": "6. Premium (~92%)"},
    {"Tipo": "CON IA + CURSOS", "Cursos": True, "Turno": "Mañana", "NSR": 50, "NJR": 380, "NIA": 20, "Desc": "7. Ultra (~93%)"},
    {"Tipo": "CON IA + CURSOS", "Cursos": True, "Turno": "Mañana", "NSR": 50, "NJR": 390, "NIA": 20, "Desc": "8. Max (~94%)"},

    # --- TARDE (Seniors Fijos = 100) ---
    {"Tipo": "CON IA + CURSOS", "Cursos": True, "Turno": "Tarde", "NSR": 100, "NJR": 440, "NIA": 20, "Desc": "1. Base (~84%)"},
    {"Tipo": "CON IA + CURSOS", "Cursos": True, "Turno": "Tarde", "NSR": 100, "NJR": 453, "NIA": 20, "Desc": "2. Pre-Low Cost (~85.5%)"},
    {"Tipo": "CON IA + CURSOS", "Cursos": True, "Turno": "Tarde", "NSR": 100, "NJR": 467, "NIA": 20, "Desc": "3. Low Cost (~87%)"},
    {"Tipo": "CON IA + CURSOS", "Cursos": True, "Turno": "Tarde", "NSR": 100, "NJR": 478, "NIA": 20, "Desc": "4. Intermedio 1 (~88.5%)"},
    {"Tipo": "CON IA + CURSOS", "Cursos": True, "Turno": "Tarde", "NSR": 100, "NJR": 489, "NIA": 20, "Desc": "5. Equilibrado (~90%)"},
    {"Tipo": "CON IA + CURSOS", "Cursos": True, "Turno": "Tarde", "NSR": 100, "NJR": 503, "NIA": 20, "Desc": "6. Premium (~92%)"},
    {"Tipo": "CON IA + CURSOS", "Cursos": True, "Turno": "Tarde", "NSR": 100, "NJR": 515, "NIA": 20, "Desc": "7. Ultra (~93%)"},
    {"Tipo": "CON IA + CURSOS", "Cursos": True, "Turno": "Tarde", "NSR": 100, "NJR": 530, "NIA": 20, "Desc": "8. Max (~94%)"},

    # --- NOCHE (Seniors Fijos = 50) ---
    {"Tipo": "CON IA + CURSOS", "Cursos": True, "Turno": "Noche", "NSR": 50, "NJR": 340, "NIA": 20, "Desc": "1. Base (~84%)"},
    {"Tipo": "CON IA + CURSOS", "Cursos": True, "Turno": "Noche", "NSR": 50, "NJR": 350, "NIA": 20, "Desc": "2. Pre-Low Cost (~85.5%)"},
    {"Tipo": "CON IA + CURSOS", "Cursos": True, "Turno": "Noche", "NSR": 50, "NJR": 362, "NIA": 20, "Desc": "3. Low Cost (~87%)"},
    {"Tipo": "CON IA + CURSOS", "Cursos": True, "Turno": "Noche", "NSR": 50, "NJR": 370, "NIA": 20, "Desc": "4. Intermedio 1 (~88.5%)"},
    {"Tipo": "CON IA + CURSOS", "Cursos": True, "Turno": "Noche", "NSR": 50, "NJR": 378, "NIA": 20, "Desc": "5. Equilibrado (~90%)"},
    {"Tipo": "CON IA + CURSOS", "Cursos": True, "Turno": "Noche", "NSR": 50, "NJR": 387, "NIA": 20, "Desc": "6. Premium (~92%)"},
    {"Tipo": "CON IA + CURSOS", "Cursos": True, "Turno": "Noche", "NSR": 50, "NJR": 396, "NIA": 20, "Desc": "7. Ultra (~93%)"},
    {"Tipo": "CON IA + CURSOS", "Cursos": True, "Turno": "Noche", "NSR": 50, "NJR": 405, "NIA": 20, "Desc": "8. Max (~94%)"}
]

resultados_unificados = []

generadores_ia = {
    "Madrugada": generar_ia_madrugada,
    "Mañana": generar_ia_maniana,
    "Tarde": generar_ia_tarde,
    "Noche": generar_ia_noche
}

for i, esc in enumerate(escenarios_unificados):
    print(f"[{esc['Tipo']}] {esc['Turno']} | {esc['Desc']} -> {esc['NSR']} Sr, {esc['NJR']} Jr, {esc['NIA']} IA")

    # 1. Ejecución del simulador EAE
    res = simular_turno(
        nombre_turno=esc["Turno"],
        NSR=esc["NSR"],
        NJR=esc["NJR"],
        NIA=esc["NIA"],
        fn_generar_ia=generadores_ia[esc["Turno"]],
        cursos_activos=esc["Cursos"]
    )

    # 2. Asignación de metadata
    res["Modelo"] = esc["Tipo"]
    res["Escenario"] = esc["Desc"]
    res["Seniors"] = esc["NSR"]
    res["Juniors"] = esc["NJR"]
    res["Canales IA"] = esc["NIA"]

    # 3. CÁLCULO ECONÓMICO ANUAL (TODO EN PESOS ARS)
    total_operadores = esc["NSR"] + esc["NJR"]
    costo_sueldos = (esc["NSR"] * COSTO_ANUAL_SENIOR) + (esc["NJR"] * COSTO_ANUAL_JUNIOR)
    costo_cursos = (total_operadores * COSTO_ANUAL_CURSO_POR_OP) if esc["Cursos"] else 0
    costo_ia = COSTO_ANUAL_IA if esc["NIA"] > 0 else 0

    costo_total = costo_sueldos + costo_cursos + costo_ia

    res["Sueldos (ARS)"] = f"${costo_sueldos:,.0f}"
    res["Licencia IA (ARS)"] = f"${costo_ia:,.0f}"
    res["Capacitación (ARS)"] = f"${costo_cursos:,.0f}"
    res["Costo TOTAL (ARS)"] = f"${costo_total:,.0f}"

    # 4. Validación del SLA
    sla = res["SLA (PA)"]
    if 87.0 <= sla <= 92.0:
        res["Evaluación"] = "✅ ÓPTIMO"
    elif sla > 92.0:
        res["Evaluación"] = "❌ CARO"
    else:
        res["Evaluación"] = "❌ RIESGO"

    resultados_unificados.append(res)

print("\n--- ¡SIMULACIONES COMPLETADAS! ---")

# 5. Formateo y Visualización de DataFrame
df_unificado = pd.DataFrame(resultados_unificados)

# Reordenamos columnas para facilitar la lectura y comparación económica
columnas_orden = [
    "Modelo", "Turno", "Escenario", "Seniors", "Juniors", "Canales IA",
    "SLA (PA)", "Evaluación", "Costo TOTAL (ARS)", "Sueldos (ARS)",
    "Licencia IA (ARS)", "Capacitación (ARS)", "Arrepentidos", "PTO General (%)"
]
df_unificado = df_unificado[columnas_orden]

display(df_unificado)

df_unificado.to_excel("Comparativa_Modelos_CallCenter.xlsx", index=False)